
#List of curio slot type settings
[[curiosSettings]]
	identifier = "charm"

[[curiosSettings]]
	identifier = "charm"

[[curiosSettings]]
	identifier = "hands"

[[curiosSettings]]
	identifier = "head"

[[curiosSettings]]
	identifier = "magnet"

[[curiosSettings]]
	identifier = "necklace"
